/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import java.awt.Color;

/**
 *
 * @author octaviolopez
 */
public class JFraClientes extends javax.swing.JFrame {

    /**
     * Creates new form JFraClientes
     */
    public JFraClientes() {
        initComponents();
        jTFApellido.setBackground(new Color(0,0,0,0));
        jTFNombre.setBackground(new Color(0,0,0,0));
        jTFId.setBackground(new Color(0,0,0,0));
        jTFTelefono.setBackground(new Color(0,0,0,0));
        
        
        
        scroll.setOpaque(false);
        scroll.getViewport().setOpaque(false);
        scroll.setBorder(null);
        
        
        
        
        jTxADireccion.setBackground(new Color(0,0,0,0));
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator4 = new javax.swing.JSeparator();
        jTFApellido = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jTFNombre = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jTFId = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jTFTelefono = new javax.swing.JTextField();
        jCbSexo = new javax.swing.JComboBox<>();
        jCbSexo1 = new javax.swing.JComboBox<>();
        scroll = new javax.swing.JScrollPane();
        jTxADireccion = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jPnlNuevoCliente = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPnlGuardarCliente = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPnlEditarCliente = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPnlEliminarCliente = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPnlCancelarCliente = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 190, 10));

        jTFApellido.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        jTFApellido.setForeground(new java.awt.Color(255, 255, 255));
        jTFApellido.setText("Ingresar Apellido");
        jTFApellido.setBorder(null);
        jTFApellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTFApellidoMousePressed(evt);
            }
        });
        getContentPane().add(jTFApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 180, -1));
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 190, 10));

        jTFNombre.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        jTFNombre.setForeground(new java.awt.Color(255, 255, 255));
        jTFNombre.setText("Ingresar Nombre");
        jTFNombre.setBorder(null);
        jTFNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTFNombreMousePressed(evt);
            }
        });
        getContentPane().add(jTFNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 180, -1));
        getContentPane().add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 190, 10));

        jTFId.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        jTFId.setForeground(new java.awt.Color(255, 255, 255));
        jTFId.setText("Id:");
        jTFId.setBorder(null);
        jTFId.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTFIdMousePressed(evt);
            }
        });
        getContentPane().add(jTFId, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 30, -1));
        getContentPane().add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 190, 10));

        jTFTelefono.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        jTFTelefono.setForeground(new java.awt.Color(255, 255, 255));
        jTFTelefono.setText("Ingresar Telefono");
        jTFTelefono.setBorder(null);
        jTFTelefono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTFTelefonoMousePressed(evt);
            }
        });
        getContentPane().add(jTFTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 180, -1));

        jCbSexo.setBackground(new java.awt.Color(255, 255, 255));
        jCbSexo.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        jCbSexo.setForeground(new java.awt.Color(255, 255, 255));
        jCbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jCbSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 190, -1));

        jCbSexo1.setBackground(new java.awt.Color(255, 255, 255));
        jCbSexo1.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        jCbSexo1.setForeground(new java.awt.Color(255, 255, 255));
        jCbSexo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jCbSexo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 190, -1));

        jTxADireccion.setColumns(20);
        jTxADireccion.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        jTxADireccion.setForeground(new java.awt.Color(255, 255, 255));
        jTxADireccion.setRows(5);
        jTxADireccion.setText("Direccion");
        jTxADireccion.setToolTipText("");
        jTxADireccion.setOpaque(false);
        jTxADireccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTxADireccionMousePressed(evt);
            }
        });
        scroll.setViewportView(jTxADireccion);

        getContentPane().add(scroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 320, 100));

        jLabel2.setFont(new java.awt.Font("Avenir Next", 0, 24)); // NOI18N
        jLabel2.setText("Area Clientes");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jPnlNuevoCliente.setBackground(new java.awt.Color(36, 47, 70));
        jPnlNuevoCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPnlNuevoClienteMousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPnlNuevoClienteMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPnlNuevoClienteMouseEntered(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nuevo");
        jPnlNuevoCliente.add(jLabel4);

        getContentPane().add(jPnlNuevoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, 130, 30));

        jPnlGuardarCliente.setBackground(new java.awt.Color(36, 47, 70));
        jPnlGuardarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPnlGuardarClienteMousePressed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Guardar");
        jPnlGuardarCliente.add(jLabel5);

        getContentPane().add(jPnlGuardarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 160, 130, 30));

        jPnlEditarCliente.setBackground(new java.awt.Color(36, 47, 70));
        jPnlEditarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPnlEditarClienteMousePressed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Editar");
        jPnlEditarCliente.add(jLabel6);

        getContentPane().add(jPnlEditarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 220, 130, 30));

        jPnlEliminarCliente.setBackground(new java.awt.Color(36, 47, 70));
        jPnlEliminarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPnlEliminarClienteMousePressed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Eliminar");
        jPnlEliminarCliente.add(jLabel7);

        getContentPane().add(jPnlEliminarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 280, 130, 30));

        jPnlCancelarCliente.setBackground(new java.awt.Color(36, 47, 70));
        jPnlCancelarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPnlCancelarClienteMousePressed(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Cancelar");
        jPnlCancelarCliente.add(jLabel8);

        getContentPane().add(jPnlCancelarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, 130, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Clientes.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFApellidoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFApellidoMousePressed
        // TODO add your handling code here:
        jTFApellido.setText("");
    }//GEN-LAST:event_jTFApellidoMousePressed

    private void jTFNombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFNombreMousePressed
        // TODO add your handling code here:
        jTFNombre.setText("");
    }//GEN-LAST:event_jTFNombreMousePressed

    private void jTFIdMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFIdMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFIdMousePressed

    private void jTFTelefonoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFTelefonoMousePressed
        // TODO add your handling code here:
        jTFTelefono.setText("");
    }//GEN-LAST:event_jTFTelefonoMousePressed

    private void jTxADireccionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTxADireccionMousePressed
        // TODO add your handling code here:
        jTxADireccion.setText("");
    }//GEN-LAST:event_jTxADireccionMousePressed

    private void jPnlNuevoClienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPnlNuevoClienteMousePressed
        // TODO add your handling code here:    
        jPnlNuevoCliente.setBackground(new Color(0,153,51));
        jPnlGuardarCliente.setBackground(new Color(36,47,70));
        jPnlEditarCliente.setBackground(new Color(36,47,70));
        jPnlEliminarCliente.setBackground(new Color(36,47,70));
        jPnlCancelarCliente.setBackground(new Color(36,47,70));
        
        
    }//GEN-LAST:event_jPnlNuevoClienteMousePressed

    private void jPnlNuevoClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPnlNuevoClienteMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jPnlNuevoClienteMouseEntered

    private void jPnlNuevoClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPnlNuevoClienteMouseExited
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jPnlNuevoClienteMouseExited

    private void jPnlGuardarClienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPnlGuardarClienteMousePressed
        // TODO add your handling code here:
        jPnlGuardarCliente.setBackground(new Color(0,153,51));
        jPnlNuevoCliente.setBackground(new Color(36,47,70));
        jPnlEditarCliente.setBackground(new Color(36,47,70));
        jPnlEliminarCliente.setBackground(new Color(36,47,70));
        jPnlCancelarCliente.setBackground(new Color(36,47,70));
        
        
    }//GEN-LAST:event_jPnlGuardarClienteMousePressed

    private void jPnlEditarClienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPnlEditarClienteMousePressed
        // TODO add your handling code here:
        jPnlEditarCliente.setBackground(new Color(0,153,51));
        jPnlGuardarCliente.setBackground(new Color(36,47,70));
        jPnlNuevoCliente.setBackground(new Color(36,47,70));
        jPnlEliminarCliente.setBackground(new Color(36,47,70));
        jPnlCancelarCliente.setBackground(new Color(36,47,70));
        
    }//GEN-LAST:event_jPnlEditarClienteMousePressed

    private void jPnlEliminarClienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPnlEliminarClienteMousePressed
        // TODO add your handling code here:
        jPnlEliminarCliente.setBackground(new Color(0,153,51));
        jPnlGuardarCliente.setBackground(new Color(36,47,70));
        jPnlNuevoCliente.setBackground(new Color(36,47,70));
        jPnlEditarCliente.setBackground(new Color(36,47,70));
        jPnlCancelarCliente.setBackground(new Color(36,47,70));
        
    }//GEN-LAST:event_jPnlEliminarClienteMousePressed

    private void jPnlCancelarClienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPnlCancelarClienteMousePressed
        // TODO add your handling code here:
        jPnlCancelarCliente.setBackground(new Color(0,153,51));
        jPnlGuardarCliente.setBackground(new Color(36,47,70));
        jPnlNuevoCliente.setBackground(new Color(36,47,70));
        jPnlEditarCliente.setBackground(new Color(36,47,70));
        jPnlEliminarCliente.setBackground(new Color(36,47,70));
        
    }//GEN-LAST:event_jPnlCancelarClienteMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFraClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFraClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFraClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFraClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFraClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jCbSexo;
    private javax.swing.JComboBox<String> jCbSexo1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPnlCancelarCliente;
    private javax.swing.JPanel jPnlEditarCliente;
    private javax.swing.JPanel jPnlEliminarCliente;
    private javax.swing.JPanel jPnlGuardarCliente;
    private javax.swing.JPanel jPnlNuevoCliente;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextField jTFApellido;
    private javax.swing.JTextField jTFId;
    private javax.swing.JTextField jTFNombre;
    private javax.swing.JTextField jTFTelefono;
    private javax.swing.JTextArea jTxADireccion;
    private javax.swing.JScrollPane scroll;
    // End of variables declaration//GEN-END:variables
}
