/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import java.awt.Color;
import java.awt.event.ActionEvent;
import static javafx.scene.paint.Color.color;
import static javafx.scene.paint.Color.color;

/**
 *
 * @author AG
 */
public class JFraMdi extends javax.swing.JFrame {

    /**
     * 
     * 
     * Creates new form JFraMdi
     */
    public JFraMdi() {
        initComponents();
        this.jPlClientes.setVisible(false);
        
        jTFApellido.setBackground(new Color(0,0,0,0));
        jTFNombre.setBackground(new Color(0,0,0,0));
        jTFId.setBackground(new Color(0,0,0,0));
        jTFTelefono.setBackground(new Color(0,0,0,0));
        
        scroll.setOpaque(false);
        scroll.getViewport().setOpaque(false);
        scroll.setBorder(null);
        
        
        
        
        jTxADireccion.setBackground(new Color(0,0,0,0));
        
        
        
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator4 = new javax.swing.JSeparator();
        jPlPrincipal = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPlClientes = new javax.swing.JPanel();
        jPnlEditarCliente = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jCbSexo1 = new javax.swing.JComboBox<>();
        jPnlGuardarCliente = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel34 = new javax.swing.JLabel();
        jTFNombre = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jPnlNuevoCliente = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jTFApellido = new javax.swing.JTextField();
        jTFId = new javax.swing.JTextField();
        jCbSexo = new javax.swing.JComboBox<>();
        jPnlEliminarCliente = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jPnlCancelarCliente = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jTFTelefono = new javax.swing.JTextField();
        scroll = new javax.swing.JScrollPane();
        jTxADireccion = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPlPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        jPlPrincipal.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jPlPrincipalComponentAdded(evt);
            }
        });
        jPlPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        jLabel14.setText("Informacion de estos.");
        jPlPrincipal.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, -1, -1));

        jLabel15.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        jLabel15.setText("Nuestros Clientes Y sus Respectivas");
        jPlPrincipal.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jLabel16.setFont(new java.awt.Font("Avenir Next", 0, 18)); // NOI18N
        jLabel16.setText("Cuentas");
        jPlPrincipal.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, -1, -1));

        jLabel18.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        jLabel18.setText("Systema pensado para llevar Registro de ");
        jPlPrincipal.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jPlPrincipal.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 290, -1));

        jLabel17.setFont(new java.awt.Font("Avenir Next", 0, 18)); // NOI18N
        jLabel17.setText("Bienvenido a Banco Xyz System");
        jPlPrincipal.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jLabel19.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        jLabel19.setText("De Clientes.");
        jPlPrincipal.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, -1, -1));

        jLabel20.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        jLabel20.setText("De nuestros Clientes para poder tener");
        jPlPrincipal.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, -1, -1));
        jPlPrincipal.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));
        jPlPrincipal.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        jPlPrincipal.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 290, -1));

        jLabel22.setFont(new java.awt.Font("Avenir Next", 0, 18)); // NOI18N
        jLabel22.setText("Clientes");
        jPlPrincipal.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        jLabel23.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        jLabel23.setText("Nos Aseguramos de Tomar los Datos ");
        jPlPrincipal.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, -1));

        jLabel24.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        jLabel24.setText("Informacion de Cuentas al dia,");
        jPlPrincipal.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, -1, -1));

        jLabel25.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        jLabel25.setText("Registro y control de cuentas");
        jPlPrincipal.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, -1, -1));
        jPlPrincipal.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 140, -1));
        jPlPrincipal.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, -1, -1));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/caja-fuerte.png"))); // NOI18N
        jPlPrincipal.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, -1, -1));

        jLabel13.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        jLabel13.setText("Cuentas bancarias de la mejor manera.");
        jPlPrincipal.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/banco.png"))); // NOI18N
        jPlPrincipal.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, -1, -1));

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/servicio-al-cliente.png"))); // NOI18N
        jPlPrincipal.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dinero.png"))); // NOI18N
        jPlPrincipal.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        getContentPane().add(jPlPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 700, 480));

        jPanel1.setBackground(new java.awt.Color(36, 47, 55));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Avenir Next", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Banco XYZ System");
        jLabel1.setAutoscrolls(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 700, 40));

        jPlClientes.setBackground(new java.awt.Color(255, 255, 255));
        jPlClientes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPnlEditarCliente.setBackground(new java.awt.Color(36, 47, 70));
        jPnlEditarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPnlEditarClienteMousePressed(evt);
            }
        });

        jLabel37.setBackground(new java.awt.Color(255, 255, 255));
        jLabel37.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("Editar");
        jPnlEditarCliente.add(jLabel37);

        jPlClientes.add(jPnlEditarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 218, 130, 30));

        jCbSexo1.setBackground(new java.awt.Color(255, 255, 255));
        jCbSexo1.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        jCbSexo1.setForeground(new java.awt.Color(255, 255, 255));
        jCbSexo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPlClientes.add(jCbSexo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 190, -1));

        jPnlGuardarCliente.setBackground(new java.awt.Color(36, 47, 70));
        jPnlGuardarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPnlGuardarClienteMousePressed(evt);
            }
        });

        jLabel36.setBackground(new java.awt.Color(255, 255, 255));
        jLabel36.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Guardar");
        jPnlGuardarCliente.add(jLabel36);

        jPlClientes.add(jPnlGuardarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 160, 130, 30));
        jPlClientes.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 190, 10));

        jLabel34.setFont(new java.awt.Font("Avenir Next", 0, 24)); // NOI18N
        jLabel34.setText("Area Clientes");
        jPlClientes.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jTFNombre.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        jTFNombre.setForeground(new java.awt.Color(255, 255, 255));
        jTFNombre.setText("Ingresar Nombre");
        jTFNombre.setBorder(null);
        jTFNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTFNombreMousePressed(evt);
            }
        });
        jPlClientes.add(jTFNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 180, -1));
        jPlClientes.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 190, 10));
        jPlClientes.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 190, 10));
        jPlClientes.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 190, 10));

        jPnlNuevoCliente.setBackground(new java.awt.Color(36, 47, 70));
        jPnlNuevoCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPnlNuevoClienteMousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPnlNuevoClienteMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPnlNuevoClienteMouseEntered(evt);
            }
        });

        jLabel35.setBackground(new java.awt.Color(255, 255, 255));
        jLabel35.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Nuevo");
        jPnlNuevoCliente.add(jLabel35);

        jPlClientes.add(jPnlNuevoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, 130, 30));

        jTFApellido.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        jTFApellido.setForeground(new java.awt.Color(255, 255, 255));
        jTFApellido.setText("Ingresar Apellido");
        jTFApellido.setBorder(null);
        jTFApellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTFApellidoMousePressed(evt);
            }
        });
        jPlClientes.add(jTFApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 180, -1));

        jTFId.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        jTFId.setForeground(new java.awt.Color(255, 255, 255));
        jTFId.setText("Id:");
        jTFId.setBorder(null);
        jTFId.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTFIdMousePressed(evt);
            }
        });
        jPlClientes.add(jTFId, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 30, -1));

        jCbSexo.setBackground(new java.awt.Color(255, 255, 255));
        jCbSexo.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        jCbSexo.setForeground(new java.awt.Color(255, 255, 255));
        jCbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPlClientes.add(jCbSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 190, -1));

        jPnlEliminarCliente.setBackground(new java.awt.Color(36, 47, 70));
        jPnlEliminarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPnlEliminarClienteMousePressed(evt);
            }
        });

        jLabel38.setBackground(new java.awt.Color(255, 255, 255));
        jLabel38.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("Eliminar");
        jPnlEliminarCliente.add(jLabel38);

        jPlClientes.add(jPnlEliminarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 280, 130, 30));

        jPnlCancelarCliente.setBackground(new java.awt.Color(36, 47, 70));
        jPnlCancelarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPnlCancelarClienteMousePressed(evt);
            }
        });

        jLabel39.setBackground(new java.awt.Color(255, 255, 255));
        jLabel39.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("Cancelar");
        jPnlCancelarCliente.add(jLabel39);

        jPlClientes.add(jPnlCancelarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, 130, 30));

        jTFTelefono.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        jTFTelefono.setForeground(new java.awt.Color(255, 255, 255));
        jTFTelefono.setText("Ingresar Telefono");
        jTFTelefono.setBorder(null);
        jTFTelefono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTFTelefonoMousePressed(evt);
            }
        });
        jPlClientes.add(jTFTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 180, -1));

        jTxADireccion.setColumns(20);
        jTxADireccion.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        jTxADireccion.setForeground(new java.awt.Color(255, 255, 255));
        jTxADireccion.setRows(5);
        jTxADireccion.setText("Direccion");
        jTxADireccion.setToolTipText("");
        jTxADireccion.setOpaque(false);
        jTxADireccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTxADireccionMousePressed(evt);
            }
        });
        scroll.setViewportView(jTxADireccion);

        jPlClientes.add(scroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 320, 100));

        jPanel4.setBackground(new java.awt.Color(255, 102, 0));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel41.setBackground(new java.awt.Color(255, 255, 255));
        jLabel41.setFont(new java.awt.Font("Avenir Next", 0, 12)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("  ↓ Vizualizar");
        jPanel4.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jPlClientes.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 130, 40));

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Clientes.png"))); // NOI18N
        jPlClientes.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 480));

        getContentPane().add(jPlClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 700, 480));

        jPanel2.setBackground(new java.awt.Color(36, 47, 70));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setAlignmentX(0.1F);
        jSeparator1.setAlignmentY(0.1F);
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 140, -1));
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, -1, -1));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator2.setAlignmentX(0.3F);
        jSeparator2.setAlignmentY(0.3F);
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 150, -1));

        jLabel4.setFont(new java.awt.Font("Avenir Next", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 51));
        jLabel4.setText("Fecha:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, -1, -1));

        jLabel5.setFont(new java.awt.Font("Avenir Next", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Usuario");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, -1, 20));

        jLabel2.setFont(new java.awt.Font("Avenir Next", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Menú");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, -1, 20));

        jLabel6.setFont(new java.awt.Font("Avenir Next", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 51));
        jLabel6.setText("Usuario Activo:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, -1));
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        jPanel3.setBackground(new java.awt.Color(36, 47, 70));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel3MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel3MouseEntered(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Avenir Next", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Clientes");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 24));
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 200, 40));

        jPanel5.setBackground(new java.awt.Color(36, 47, 70));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel5MousePressed(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel5MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel5MouseEntered(evt);
            }
        });
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Avenir Next", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Cuenta");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 200, 40));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bank-flat/64x64.png"))); // NOI18N
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_jPanel5MouseEntered

    private void jPanel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_jPanel5MouseExited

    private void jPanel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MousePressed
        // TODO add your handling code here:
        jPanel5.setBackground(new Color(0,153,51));
        jPanel3.setBackground(new Color(36,47,70));
    }//GEN-LAST:event_jPanel5MousePressed

    private void jPanel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_jPanel3MouseEntered

    private void jPanel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_jPanel3MouseExited

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
        // TODO add your handling code here
        jPanel3.setBackground(new Color(0,153,51));
        jPanel5.setBackground(new Color(36,47,70));
    }//GEN-LAST:event_jPanel3MousePressed

    private void jTFApellidoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFApellidoMousePressed
        // TODO add your handling code here:
        jTFApellido.setText("");
    }//GEN-LAST:event_jTFApellidoMousePressed

    private void jTFNombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFNombreMousePressed
        // TODO add your handling code here:
        jTFNombre.setText("");
    }//GEN-LAST:event_jTFNombreMousePressed

    private void jTFIdMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFIdMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFIdMousePressed

    private void jTFTelefonoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFTelefonoMousePressed
        // TODO add your handling code here:
        jTFTelefono.setText("");
    }//GEN-LAST:event_jTFTelefonoMousePressed

    private void jTxADireccionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTxADireccionMousePressed
        // TODO add your handling code here:
        jTxADireccion.setText("");
    }//GEN-LAST:event_jTxADireccionMousePressed

    private void jPnlNuevoClienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPnlNuevoClienteMousePressed
        // TODO add your handling code here:
        jPnlNuevoCliente.setBackground(new Color(0,153,51));
        jPnlGuardarCliente.setBackground(new Color(36,47,70));
        jPnlEditarCliente.setBackground(new Color(36,47,70));
        jPnlEliminarCliente.setBackground(new Color(36,47,70));
        jPnlCancelarCliente.setBackground(new Color(36,47,70));

    }//GEN-LAST:event_jPnlNuevoClienteMousePressed

    private void jPnlNuevoClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPnlNuevoClienteMouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_jPnlNuevoClienteMouseExited

    private void jPnlNuevoClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPnlNuevoClienteMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_jPnlNuevoClienteMouseEntered

    private void jPnlGuardarClienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPnlGuardarClienteMousePressed
        // TODO add your handling code here:
        jPnlGuardarCliente.setBackground(new Color(0,153,51));
        jPnlNuevoCliente.setBackground(new Color(36,47,70));
        jPnlEditarCliente.setBackground(new Color(36,47,70));
        jPnlEliminarCliente.setBackground(new Color(36,47,70));
        jPnlCancelarCliente.setBackground(new Color(36,47,70));

    }//GEN-LAST:event_jPnlGuardarClienteMousePressed

    private void jPnlEditarClienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPnlEditarClienteMousePressed
        // TODO add your handling code here:
        jPnlEditarCliente.setBackground(new Color(0,153,51));
        jPnlGuardarCliente.setBackground(new Color(36,47,70));
        jPnlNuevoCliente.setBackground(new Color(36,47,70));
        jPnlEliminarCliente.setBackground(new Color(36,47,70));
        jPnlCancelarCliente.setBackground(new Color(36,47,70));

    }//GEN-LAST:event_jPnlEditarClienteMousePressed

    private void jPnlEliminarClienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPnlEliminarClienteMousePressed
        // TODO add your handling code here:
        jPnlEliminarCliente.setBackground(new Color(0,153,51));
        jPnlGuardarCliente.setBackground(new Color(36,47,70));
        jPnlNuevoCliente.setBackground(new Color(36,47,70));
        jPnlEditarCliente.setBackground(new Color(36,47,70));
        jPnlCancelarCliente.setBackground(new Color(36,47,70));

    }//GEN-LAST:event_jPnlEliminarClienteMousePressed

    private void jPnlCancelarClienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPnlCancelarClienteMousePressed
        // TODO add your handling code here:
        jPnlCancelarCliente.setBackground(new Color(0,153,51));
        jPnlGuardarCliente.setBackground(new Color(36,47,70));
        jPnlNuevoCliente.setBackground(new Color(36,47,70));
        jPnlEditarCliente.setBackground(new Color(36,47,70));
        jPnlEliminarCliente.setBackground(new Color(36,47,70));

    }//GEN-LAST:event_jPnlCancelarClienteMousePressed

    private void jPlPrincipalComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jPlPrincipalComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jPlPrincipalComponentAdded

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        // TODO add your handling code here:
        this.jPlClientes.setVisible(true);
        this.jPlPrincipal.setVisible(false);
        
       
        
    }//GEN-LAST:event_jPanel3MouseClicked

  
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFraMdi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFraMdi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFraMdi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFraMdi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFraMdi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jCbSexo;
    private javax.swing.JComboBox<String> jCbSexo1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPlClientes;
    private javax.swing.JPanel jPlPrincipal;
    private javax.swing.JPanel jPnlCancelarCliente;
    private javax.swing.JPanel jPnlEditarCliente;
    private javax.swing.JPanel jPnlEliminarCliente;
    private javax.swing.JPanel jPnlGuardarCliente;
    private javax.swing.JPanel jPnlNuevoCliente;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField jTFApellido;
    private javax.swing.JTextField jTFId;
    private javax.swing.JTextField jTFNombre;
    private javax.swing.JTextField jTFTelefono;
    private javax.swing.JTextArea jTxADireccion;
    private javax.swing.JScrollPane scroll;
    // End of variables declaration//GEN-END:variables

    private static class jBtnClientes {

        private static void setBackground(Color color) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        public jBtnClientes() {
        }
    }
}
